### ISSUE TITLE
Form id must be specified in the tag

### ISSUE THREAD

**Issue by mattions** [FHBrandenburg/django-bootstrap-dynamic-formsets#1]
Hi, 
thank you for this app, it is very useful.

I found a little issue the id of the form is fixed in the javascript to `id_form` 

(https://github.com/FHBrandenburg/django-bootstrap-dynamic-formsets/blob/master/django_bootstrap_dynamic_formsets/templates/django_bootstrap_dynamic_formsets/dynamic_formsets_js.html#L152)

In my app instead it gets the name `id_guest_set` (I am using inline formset).
So the total amount of forms does never get changed.
I'm wondering if we could update the template tags for the formset, so the id of the created form can be passed as a variable. 

What do you think?

This the html for reference

```
<input id="id_guest_set-TOTAL_FORMS" name="guest_set-TOTAL_FORMS" type="hidden" value="1" />
<input id="id_guest_set-INITIAL_FORMS" name="guest_set-INITIAL_FORMS" type="hidden" value="0" />
<input id="id_guest_set-MIN_NUM_FORMS" name="guest_set-MIN_NUM_FORMS" type="hidden" value="1" />
<input id="id_guest_set-MAX_NUM_FORMS" name="guest_set-MAX_NUM_FORMS" type="hidden" value="1000" />
```

**Comment by danielw92** [comment]
Hello Michele,
you're welcome! It's good to see that there are people out there who actually use it :)

Your pull request looks good to me, I just did a few quick tests here, so thank you for the fix/enhancement. One question for you, though: The changes to the bootstrap_dynamic_formset template tag appear to be not necessary, or am I missing something here? I am referring to the `id_formset` parameter, specifically. What do you think?

Thanks again!

**Comment by mattions** [comment]
Nope, you right.

I've just missed that when I decided to pass the whole formset to the  template_tag for the js.
It's a leftover that we could scrap.

I just remove it and update PR

**Comment by mattions** [comment]
It's done:  https://github.com/mattions/django-bootstrap-dynamic-formsets/commit/1df38118ee002272c495da4baae564597ecf71ce

merge it if you happy with it!

When are you scheduling a new release?

**Comment by danielw92** [comment]
It's in and the new release is up! Thank you very much!
