### ISSUE TITLE
support for multiple formset on one page

### ISSUE THREAD

**Issue by truhlik** [FHBrandenburg/django-bootstrap-dynamic-formsets#5]
Hi developres,

using this awesome package, but just found that there are couple JS issues if you use multiple formsets on single Web page.  Do you plan to add suport for multiple formset on single webpage?

Thank you.

**Comment by danielw92** [comment]
Hi truhlik,

I'm glad you like the package.
Unfortunately, I don't have any time to work on this package at the moment. Also, I don't use Django anymore at all and moved on to front end frameworks like React and most recently Angular 2.
However, if you would like to provide a pull request for multiple formset support, I'd be more than happy to merge it.

**Comment by truhlik** [comment]
I will try to do that and let you know. Thx

Dne středa 8. června 2016 Daniel Weis notifications@github.com napsal(a):

**Comment by MrLinio** [comment]
Any news on this @truhlik ? I'm interested too, it would be nice not to have to do it all over again.

**Comment by truhlik** [comment]
Still pushing the task in front of me :-) But I think that soon I will have to do that.

**Comment by MikeSandford** [comment]
I just submitted a pull request for this feature as I had an identical need.  It uses formset prefixes which was the only way I could think of to make it work.

**Comment by MrLinio** [comment]
Hopefully this pull request will be validated, i had to rollback on my part (had no time to make it work)
